In [3]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np

# Directory to which we'll send the data
PATH = "../Analysis Data/"

In [45]:
original_data = pd.read_csv("../Original Data/12_S╠üWIE╠ĘTOKRZYSKIE.csv")
df = original_data
df['Płeć kupującego'] = df['Płeć kupującego'].replace("bd.", np.nan)
df = original_data.dropna(subset=['Dni od zakupu','Marka','Wiek kupującego','Płeć kupującego','Ocena'])   # usunięcie wierszy z pustymi komórkami
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
df = df.reset_index(drop=True)
df.to_csv('../Analysis Data/tb-tidy.csv', index=False)   
df.to_csv('../Documents/tb-tidy.csv', index=False)

df

     Dni od zakupu       Marka  Wiek kupującego Płeć kupującego  Ocena
0                7        Beko             33.0               M    3.0
1               10        Beko             50.0               M    2.0
2               11       Tefal             36.0               M    2.5
3                3        Beko             62.0               K    2.5
4                8        Beko             38.0               M    2.0
..             ...         ...              ...             ...    ...
322             10       Tefal             34.0               M    2.0
323              8        Beko             19.0               M    2.5
324              9  Electrolux             50.0               K    3.0
325              5       Tefal             41.0               M    3.0
326             11        Beko             61.0               M    1.0

[327 rows x 5 columns]